---

- name: 'Change time zone'
  timezone:
    name: "{{time_zone}}"
    
- name: 'Template out DHCPCD YAML to configure networking'
  template: 
    src: ./templates/dhcpcd.conf.tpl
    dest: /etc/dhcpcd.conf
  become: yes
  become_method: sudo
    
- name: Reload (stop) service dhcpcd.service
  ansible.builtin.service:
    name: dhcpcd.service
    state: stopped
  become: yes
  become_method: sudo
  
- name: Reload (start) service dhcpcd.service
  ansible.builtin.service:
    name: dhcpcd.service
    state: started
  become: yes
  become_method: sudo

- name: Upgrade the OS (apt-get dist-upgrade)
  apt:
    upgrade: dist
    update_cache: yes
  become: yes
 
- name: Update all packages to latest versions
  apt:
    name: "*"
    state: latest
    update_cache: yes
  become: yes

- name: 'Install CIFS-Utils'
  apt:
    name: cifs-utils
    state: present
